import type { BudgetItem, BudgetItemImportance } from '@/types';

export const mockBudgetItems: (budgetId: string, generateTempId: () => string) => BudgetItem[] = (budgetId, generateTempId) => [
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Venue Rental',
        importance: 'innegociable',
        expected_amount: 5000,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Photography',
        importance: 'high',
        expected_amount: 2500,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Flowers',
        importance: 'normal',
        expected_amount: 1200,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Catering',
        importance: 'innegociable',
        expected_amount: 8000,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Wedding Dress',
        importance: 'high',
        expected_amount: 3000,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Groom Suit',
        importance: 'normal',
        expected_amount: 800,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Wedding Cake',
        importance: 'normal',
        expected_amount: 600,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'DJ/Music',
        importance: 'high',
        expected_amount: 1500,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Wedding Planner',
        importance: 'normal',
        expected_amount: 2000,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Transportation',
        importance: 'low',
        expected_amount: 500,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Wedding Rings',
        importance: 'innegociable',
        expected_amount: 4000,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Hair & Makeup',
        importance: 'normal',
        expected_amount: 400,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Invitations',
        importance: 'low',
        expected_amount: 300,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Decorations',
        importance: 'normal',
        expected_amount: 1000,
    },
    {
        id: generateTempId(),
        budget_id: budgetId,
        name: 'Favors',
        importance: 'low',
        expected_amount: 200,
    },
];
